# Generated by Django 4.0.5 on 2022-06-22 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('thumbnail', models.FileField(upload_to='uploads/', verbose_name='썸네일')),
                ('contents', models.TextField(verbose_name='상품 설명')),
                ('posting_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출 종료 일자')),
                ('cost', models.IntegerField(verbose_name='가격')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
