# Generated by Django 4.0.5 on 2022-06-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='username',
        ),
    ]
