# Generated by Django 4.0.5 on 2022-06-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_user_product_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='username',
            new_name='user',
        ),
    ]
