# Generated by Django 4.0.5 on 2022-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_username_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
    ]
