# Generated by Django 4.0.5 on 2022-06-22 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출 종료 일자'),
        ),
    ]
